from random import randint
# n1 = randint(0, 10)
# n2 = randint(0, 10)
# n3 = randint(0, 10)
# n4 = randint(0, 10)
# n5 = randint(0, 10)
# nt = (n1, n2, n3, n4, n5)
# print(f'Os valores sorteados foram: {nt}')
# print(f'O maior valor sorteado foi {max(nt)}')
# print(f'O menor valor sorteado foi {min(nt)}')
numeros = (randint(1, 10), randint(1, 10), randint(1, 10), randint(1, 10), randint(1, 10))

print(f'Os valores sorteados foram: {numeros}')
print(f'O maior valor sorteado foi {max(numeros)}')
print(f'O menor valor sorteado foi {min(numeros)}')
